[project]
name = "emotonalai"
version = "0.1.0"
description = "AI that behaves as if it has feelings."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-generativeai>=0.8.3",
    "speechrecognition>=3.10.4",
]
